import type { Metadata } from "next"
import "./globals.css"

import Nav from "@/components/navigation/Nav"
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
        <Toaster />
      </body>
    </html>
  )
}
